FROM node:alpine
WORKDIR /home/app
COPY ./package.json ./package.json
COPY ./webpack.config.js ./webpack.config.js
RUN npm install
COPY . .
RUN npm run build

FROM nginx
EXPOSE 9000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=0 /home/app/bin /usr/share/nginx/html
