anguage: node_js
node_js:
 - "node"
sudo: required
services:
  - docker

before-install:
  - docker build -t fpezzati/fibworker_test -f ./fibworker/Dockerfile.dev ./fibworker
  - docker build -t fpezzati/fibserver_test -f ./server/Dockerfile.dev ./server
  - docker build -t fpezzati/fibclient_test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run fpezzati/fibworker_test npm run test -- --coverage
  - docker run fpezzati/fibserver_test npm run test -- --coverage
  - docker run fpezzati/fibclient_test npm run test -- --coverage

after_success:
  - docker build -t fpezzati/fibsequence_fibworker ./fibworker -f ./fibworker/Dockerfile.prod
  - docker build -t fpezzati/fibsequence_client ./client -f ./client/Dockerfile.prod
  - docker build -t fpezzati/fibsequence_server ./server -f ./server/Dockerfile.prod
  - docker build -t fpezzati/fibsequence_nginx ./nginx -f ./nginx/Dockerfile.prod
# loggin into docker
  - echo "$dockerpwd" | docker login -u "$dockerusr" --password-stdin
# pushing images to docker hub
  - docker push fpezzati/fibsequence_fibworker
  - docker push fpezzati/fibsequence_client
  - docker push fpezzati/fibsequence_server
  - docker push fpezzati/fibsequence_nginx

deploy:
  edge: true
  provider: elasticbeanstalk
  regiorn: "us-east-2"
  app: "fibsequence"
  env: "Fibsequence-env"
  bucket_name: "elasticbeanstalk-us-east-2-481819882433"
  bucket_path: "fibsequencebucketpath"
  on:
    branch: master
  access_key_id: $awsaccesskey
  secret_access_key: $awssecretkey
